/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jesús
 */
public class Temperatura extends javax.swing.JFrame {
    
    //Atributos
    Double oper,a,b;
    String fahr, cent;
    
    
    /**
     * Creates new form Temperatura
     */
    public Temperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupConversor = new javax.swing.ButtonGroup();
        jPanelBase = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jRadioButtonFaC = new javax.swing.JRadioButton();
        jRadioButtonCaF = new javax.swing.JRadioButton();
        jTextFieldFahrenheit = new javax.swing.JTextField();
        jTextFieldCentigrados = new javax.swing.JTextField();
        jLabelFahrenheit = new javax.swing.JLabel();
        jLabelCentigrados = new javax.swing.JLabel();
        jButtonConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBase.setBackground(new java.awt.Color(204, 51, 0));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Conversor de Temperaturas");

        jRadioButtonFaC.setBackground(new java.awt.Color(102, 0, 255));
        buttonGroupConversor.add(jRadioButtonFaC);
        jRadioButtonFaC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButtonFaC.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonFaC.setText("Fahrenheit a Centigrados");
        jRadioButtonFaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFaCActionPerformed(evt);
            }
        });

        jRadioButtonCaF.setBackground(new java.awt.Color(102, 0, 255));
        buttonGroupConversor.add(jRadioButtonCaF);
        jRadioButtonCaF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButtonCaF.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonCaF.setText("Centigrados a Fahrenheit");
        jRadioButtonCaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCaFActionPerformed(evt);
            }
        });

        jTextFieldFahrenheit.setBackground(new java.awt.Color(102, 0, 255));
        jTextFieldFahrenheit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldFahrenheit.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFahrenheitActionPerformed(evt);
            }
        });

        jTextFieldCentigrados.setBackground(new java.awt.Color(102, 0, 255));
        jTextFieldCentigrados.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldCentigrados.setForeground(new java.awt.Color(0, 0, 0));

        jLabelFahrenheit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelFahrenheit.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFahrenheit.setText("Fahrenheit");

        jLabelCentigrados.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCentigrados.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCentigrados.setText("Centigrados");

        jButtonConvertir.setBackground(new java.awt.Color(51, 0, 204));
        jButtonConvertir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonConvertir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConvertir)
                    .addComponent(jRadioButtonCaF)
                    .addComponent(jRadioButtonFaC)
                    .addComponent(jLabelTitulo)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCentigrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCentigrados)
                            .addComponent(jLabelFahrenheit))))
                .addContainerGap(578, Short.MAX_VALUE))
        );

        jPanelBaseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldCentigrados, jTextFieldFahrenheit});

        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCaF)
                .addGap(18, 18, 18)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFahrenheit))
                .addGap(18, 18, 18)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCentigrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCentigrados))
                .addGap(46, 46, 46)
                .addComponent(jButtonConvertir)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jPanelBaseLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldCentigrados, jTextFieldFahrenheit});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCaFActionPerformed
        // TODO add your handling code here:
        if(this.jRadioButtonCaF.isSelected()){
            this.jTextFieldCentigrados.enable();
            this.jTextFieldFahrenheit.disable();
            this.jTextFieldCentigrados.setText("");
            this.jTextFieldFahrenheit.setText("");
            this.jTextFieldCentigrados.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonCaFActionPerformed

    private void jTextFieldFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFahrenheitActionPerformed

    private void jRadioButtonFaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFaCActionPerformed
        // TODO add your handling code here:
        if(this.jRadioButtonFaC.isSelected()){
            this.jTextFieldFahrenheit.enable();
            this.jTextFieldCentigrados.disable();
            this.jTextFieldCentigrados.setText("");
            this.jTextFieldFahrenheit.setText("");
            this.jTextFieldFahrenheit.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonFaCActionPerformed

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        // TODO add your handling code here:
        this.a = 0.0;
        this.b = 0.0;
        this.oper = 0.0;
        if(this.jRadioButtonFaC.isSelected()){
            this.fahr = this.jTextFieldFahrenheit.getText().trim();
            this.a = Double.parseDouble(fahr);
            this.oper = (this.a-32)*5/9;
            this.jTextFieldCentigrados.setText(String.format("%.3f", this.oper));
        }
        
        if(this.jRadioButtonCaF.isSelected()){
            this.cent = this.jTextFieldCentigrados.getText().trim();
            this.b = Double.parseDouble(cent);
            this.oper = (this.b*9/5)+32;
            this.jTextFieldFahrenheit.setText(String.format("%.3f", this.oper));
        }
        
        
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupConversor;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JLabel jLabelCentigrados;
    private javax.swing.JLabel jLabelFahrenheit;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JRadioButton jRadioButtonCaF;
    private javax.swing.JRadioButton jRadioButtonFaC;
    private javax.swing.JTextField jTextFieldCentigrados;
    private javax.swing.JTextField jTextFieldFahrenheit;
    // End of variables declaration//GEN-END:variables
}
